### PR TITLE
Add hash function sentence signpost for clarity

### PR DESCRIPTION
**Pull request by WizardOfAus**
Suggestion of adding a signpost topic sentence definition for hash function to improve reading clarity

### CODE REVIEW

**Comment by pet3r-pan** [comment]
**Before**
Hashes are one-way mathematical functions that take a variable length input of any size and produces a unique fixed length output called a hash value. This function is considered as 'one way' as it is very difficult to find the original input of a hash value. This is unless you try to brute force guess all existing inputs to find a matching hash value. 

**After**
_A hash function produces a deterministic fixed-size, random looking output which is called a hash. These hashes are_ one-way mathematical functions that take a variable length input of any size and produces a unique fixed length output called a hash value. This function is considered as 'one way' as it is very difficult to find the original input of a hash value. This is unless you try to brute force guess all existing inputs to find a matching hash value. 

I think your addition to this paragraph introduces undefined complexity.

You introduce a the concept of 'deterministic' yet do not define it. Without knowing what it is, it adds vagueness to the definition of hashes. I wrote about how a hash function is deterministic later in its own paragraph. I would rather introduce a hash function as a mathematical function that inputs X to output Y. I wrote it like this to in an attempt to introduce and explain concepts one at a time.

I disagree with your new definition of what a hash is. I think 'random looking output which is called a hash' is neither clear nor objective. Hence I still prefer the specific definition of: _Hashes are one-way mathematical functions that take a variable length input of any size and produces a unique fixed length output called a hash value._

Also for your addition to (Asymmetric), I don't think that is necessarily helpful. Assuming we are writing for people who do not understand the concepts being introduced, sign posting the term 'asymmetrical' will mean little to the reader until they understand the distinction between symmetric and asymmetric, which is what the section achieves.

Let me know what you think. And would love for any other thoughts.

But for those reasons I would have to disagree with your addition there.

**Comment by WizardOfAus** [comment]
@pet3r-pan I received an email of a reply you wrote but I can't see it here.

Currently it says hashes rather than hash functions. I didn't add a very long sentence so as only to make clear of the distinction between a hash and a hash function. The output and the function. In this sense this is why the hash is fixed in size and deterministic which I didn't add more to as it is defined more or less by the sentence you have after it where you wrote the function being considered 'one way'.

**Comment by pet3r-pan** [comment]
@WizardOfAus I figured I was being pedantic lol and yes, I also figured out my fault - and soon after deleted it

**Comment by WizardOfAus** [comment]
No worries :)

**Pull request merged**
