### PR TITLE
Create file structure to add images

### PR DESCRIPTION
**Pull request by WizardOfAus**
Create file structure to add images into. Will add a sample image in current directory to show what I mean.

### CODE REVIEW

**Comment by WizardOfAus** [comment]
<kbd></kbd>

Example image for the Public Key Cryptography component of Chapter 1

**Comment by DaGitNah** [comment]
Hey, still a bit new to gibhub so I am not sure which way we are setup. I learned there are two ways. First where you upload to an issue or comment. And then you just use that link.  Apparently, this link breaks when cloned. I also learned that you could have an image folder with images then just link to their paths in markdown.   This is to get around that issue. 

Maybe we could place the images in the book folder to make it easier? So like /book/images/image.1 something like that?

**Comment by WizardOfAus** [comment]
@DaGitNah yeah exactly. But for the image folder with images, we would need Carl or someone with rights to create the structure for us to do so.

**Comment by DaGitNah** [comment]
:)  Awesome. For this pull request, the directory for images is website/assets/images/chapters/01/.  I was thinking to close this pull request and opening one where the directory is website/book/images.  Unless that would interfere with the website somehow.  Then if @karlfloersch  likes it, he can merge  :D

**Pull request merged**
